apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-deployment-viewer
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "deployments"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-deployment-viewer-binding
subjects:
  - kind: ServiceAccount
    name: pod-deployment-viewer-account
roleRef:
  kind: Role
  name: pod-deployment-viewer
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-deployment-viewer-account
