apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  template:
    spec:
      containers:
      - name: wordpress 
        image: wordpress:5.6.2-test