apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: wordpress.k8s.local
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress
          servicePort: 80
      