apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-namespace
namePrefix: dev-
nameSuffix: "-001"
resources:
# - db_password.yaml
# - deploy_mysql.yaml
- deploy_wordpress.yaml
- ingress.yaml
# - namespace.yaml
# - pvc_mysql.yaml
# - pvc_wordpress.yaml
# - svc_mysql.yaml
# - svc_wordpress.yaml