apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
- db_password.yaml
- deploy_mysql.yaml
- deploy_wordpress.yaml
- ingress.yaml
- pvc_mysql.yaml
- pvc_wordpress.yaml
- svc_mysql.yaml
- svc_wordpress.yaml
- ns_prod.yaml
images:
- name: wordpress
  newTag: "1.2"
