apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base
namePrefix:
  dev-
nameSuffix:
  -v2
commonLabels:
  app: wordpress
# patchesStrategicMerge:
# - ingress.yaml
patchesJson6902:
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: ingress
  path: patch.yaml